### ISSUE TITLE
Can't load PhyloTree class

### ISSUE THREAD

**Issue by jarrTecn** [david-schaller/AsymmeTree#1]
Hello, I'm trying to run an example code of the manual:

```python
from asymmetree.datastructures import PhyloTree
```

But it raises an error:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-36d5fa50a40e> in <module>
----> 1 from asymmetree.datastructures import PhyloTree

ModuleNotFoundError: No module named 'asymmetree.datastructures'
```

I'm using python3.7

**Comment by david-schaller** [comment]
Hi Antonio, 
It seems that you have an outdated version of the manual. Are you referring to the pdf version and where did you download it?
The pdf version is no longer maintained, please use the readme here on GitHub instead.
The Error you are getting is caused by the fact that I outsourced the tree data structures and some algorithms into the package 'tralda' a while ago.
